spring:
  application:
    name: workforce-planning

  
  datasource:
    url: jdbc:postgresql://localhost:5432/workforce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always  
      
camunda:
  client:
    mode: saas
    auth:
      client-id: ${CAMUNDA_CLIENT_ID}
      client-secret: ${CAMUNDA_CLIENT_SECRET}
      region: ${CAMUNDA_REGION}
      cluster-id: ${CAMUNDA_CLUSTER_ID}
    zeebe:
      gateway-url: https://${CAMUNDA_CLUSTER_ID}.${CAMUNDA_REGION}.zeebe.camunda.io
      base-url: https://${CAMUNDA_REGION}.zeebe.camunda.io/${CAMUNDA_CLUSTER_ID}
    operate:
      base-url: https://${CAMUNDA_REGION}.operate.camunda.io/${CAMUNDA_CLUSTER_ID}
    tasklist:
      base-url: https://${CAMUNDA_REGION}.tasklist.camunda.io/${CAMUNDA_CLUSTER_ID}
    optimize:
      base-url: https://${CAMUNDA_REGION}.optimize.camunda.io/${CAMUNDA_CLUSTER_ID}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: jriw rswf amuk okne   
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
