spring:
  application:
    name: workforce-planning

  
  datasource:
    url: jdbc:postgresql://localhost:5432/workforce-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never  
      
camunda:
  client:
    mode: saas
    auth:
      client-id: "cZFm5ceEo7opsxhcReoVjkJvAE3bDKB7"
      client-secret: "8kDwj.nAsqE_4r5cZP~xgU7IAyoLhRsybCSoy4b5dOa~c0ytCUM8K9S_hY8f4mgH"
      region: "lhr-1"
      cluster-id: "b400f927-27b1-4492-9ca0-3b0c0970bcd8"
    zeebe:
      gateway-url: "https://b400f927-27b1-4492-9ca0-3b0c0970bcd8.lhr-1.zeebe.camunda.io"
      base-url: "https://lhr-1.zeebe.camunda.io/b400f927-27b1-4492-9ca0-3b0c0970bcd8"
    operate:
      base-url: "https://lhr-1.operate.camunda.io/b400f927-27b1-4492-9ca0-3b0c0970bcd8"
    tasklist:
      base-url: "https://lhr-1.tasklist.camunda.io/b400f927-27b1-4492-9ca0-3b0c0970bcd8"
    optimize:
      base-url: "https://lhr-1.optimize.camunda.io/b400f927-27b1-4492-9ca0-3b0c0970bcd8"

  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: jriw rswf amuk okne   
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
