spring:
  application:
    name: workforce-planning

  sql:
    init:
      mode: never
      #mode: never

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.qxcvxtbxdhhixagimhak
    password: 'FRAU@20242025'
    driver-class-name: org.postgresql.Driver


  jpa:
   
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: ljut vmip xiqa xxsv   
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

camunda:
  client:
    mode: saas
    cluster-id: bca9fda6-8d74-494e-bbd7-d62c25f5b160
    region: sin-1
    auth:
      client-id: vVhXO-DdEmix.d.eerh3JX~JdYrsYNaL
      client-secret: E96o36zUop0JxxEf8ig_kiSGygKNtbWf~rxTNVeH.09vjG03BTsH.qZ4qb.mKNey
    zeebe:
      
      request-timeout: 60s
      default-request-timeout: 60s
      keep-alive: 60s
# camunda:
#   client:
#     mode: saas
#     cluster-id: ece89c82-5dfa-4736-8beb-97335792858d
#     region: sin-1
#     auth:
#       client-id: aIaQ~q6v9zUQ7frCVWAX~Rz.hQoA.bAA
#       client-secret: POFwESBE0noMniqolImdrh8GzTOa6T7fsawO.hst_BDHJP7wSE0LHBbxywNXz~Oe
#     zeebe:
      
#       request-timeout: 60s



  
app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 3600000


# for mock testing 

integration: 
  team3b:
    base-url: https://webhook.site
    request-path: b20971f6-0d6f-4142-9e82-9b4e8a4a1420

