server:
  port: ${PORT:8080}

spring:
  application:
    name: workforce-planning

  sql:
    init:
      mode: always
      #mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/workforce-planning 
    username: postgres
    password: FRAU20242025
    driver-class-name: org.postgresql.Driver


  jpa:
   
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: ljut vmip xiqa xxsv   
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

camunda:
  client:
    mode: saas
    cluster-id: bca9fda6-8d74-494e-bbd7-d62c25f5b160
    region: sin-1
    auth:
      client-id: vVhXO-DdEmix.d.eerh3JX~JdYrsYNaL
      client-secret: E96o36zUop0JxxEf8ig_kiSGygKNtbWf~rxTNVeH.09vjG03BTsH.qZ4qb.mKNey
    zeebe:
      
      request-timeout: 60s
      default-request-timeout: 60s
      keep-alive: 60s

app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 3600000


# for mock testing 

integration: 
  team3b:
    base-url: "https://webhook.site/"
    request-path: "b20971f6-0d6f-4142-9e82-9b4e8a4a1420"
    decision-path: "b20971f6-0d6f-4142-9e82-9b4e8a4a1420"

