spring:
  application:
    name: workforce-planning

  sql:
    init:
      mode: always
      #mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/workforce-planning 
    username: postgres
    password: FRAU20242025
    driver-class-name: org.postgresql.Driver

  jpa:
   
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: ljut vmip xiqa xxsv   
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

camunda:
  client:
    mode: saas
    cluster-id: ece89c82-5dfa-4736-8beb-97335792858d
    region: sin-1
    auth:
      client-id: aIaQ~q6v9zUQ7frCVWAX~Rz.hQoA.bAA
      client-secret: POFwESBE0noMniqolImdrh8GzTOa6T7fsawO.hst_BDHJP7wSE0LHBbxywNXz~Oe
    zeebe:
      
      request-timeout: 60s


  

app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 3600000


# for mock testing 

integration: 
  team3b:
    base-url: http://localhost:8080
    request-path: /api/group1/workforce-request