server:
  port: ${PORT:8080}

spring:
  application:
    name: workforce-planning

  sql:
    init:
      mode: never
      #mode: never

  datasource:
      url: jdbc:postgresql://dpg-d5sua7ogjchc73b859ng-a.frankfurt-postgres.render.com:5432/postgresworkforcedb
      username: postgresworkforcedb
      password: DrlWCp5gyrPY71KThYyHShVSXTvqeyer
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 2       # Keep this low for Supabase Free Tier
        minimum-idle: 1
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000


  jpa:
   
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true 
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: anushkasen9876543567@gmail.com
    password: ljut vmip xiqa xxsv   
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

camunda:
  client:
    mode: saas
    cluster-id: bca9fda6-8d74-494e-bbd7-d62c25f5b160
    region: sin-1
    auth:
      client-id: vVhXO-DdEmix.d.eerh3JX~JdYrsYNaL
      client-secret: E96o36zUop0JxxEf8ig_kiSGygKNtbWf~rxTNVeH.09vjG03BTsH.qZ4qb.mKNey
    zeebe:
      request-timeout: 60s
      default-request-timeout: 20s
      keep-alive: 45s

app:
  jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 3600000


# for mock testing 

integration: 
  team3b:
    base-url: "https://service-management-tool.onrender.com/"
    request-path: "api/integration/group1/workforce-request"
    decision-path: "api/integration/group1/decision"
